---
- name: Gather Cisco IOS Facts
  hosts: staging
  gather_facts: no
  connection: network_cli
  vars:
    configure_logging: true
    configure_vlans: true
    configure_domain: true
    configure_radius_server_group: true
    configure_tacacs_server_group: true
    configure_global: true
    configure_span_tree: true
    configure_banner: true
    configure_interfaces: true
    configure_layer3_interfaces: true
    configure_user_ports: false
    configure_ospf: true
  roles: 
    - configureSwitch

- name: Gather Cisco IOS Facts
  hosts: csw
  gather_facts: no
  connection: network_cli
  vars:
    configure_static_routes: true
    configure_ospf_core: true
  roles: 
    - configureSwitch