---
- name: Gather Cisco IOS Facts
  hosts: staging
  gather_facts: no
  connection: network_cli
  vars:
    configure_logging: false
    configure_vlans: false
    configure_domain: false
    configure_radius_server_group: false
    configure_tacacs_server_group: false
    configure_global: false
    configure_span_tree: false
    configure_interfaces: false
    configure_layer3_interfaces: false
    configure_user_ports: false
    configure_ospf: false
    configure_banner: false
  roles: 
    - configureSwitch

- name: Gather Cisco IOS Facts
  hosts: core_switches
  gather_facts: no
  connection: network_cli
  vars:
    configure_static_routes: false
    configure_ospf_core: false
  roles: 
    - configureSwitch