---
- name: Gather Cisco IOS Facts
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect IOS facts
      ios_facts:
        gather_subset: all

    - name: Print all gathered facts
      debug:
        var: ansible_facts
