---
- name: Setting no switchport on L3 interfaces
  cisco.ios.ios_config:
    lines:
      - no switchport
    parents: "interface {{ item.key }}"
  loop: "{{ lookup('dict', hostvars[inventory_hostname]['interfaces']) }}"
  when: item.value.physical_interface is defined and item.value.physical_interface

- name: Setting L3 interface configurations
  cisco.ios.ios_config:
    lines:
      - no ip redirects
      - no ip unreachables
      - no ip proxy-arp
    parents: "interface {{ item.key }}"
  loop: "{{ lookup('dict', hostvars[inventory_hostname]['interfaces']) }}"
  when: item.value.layer3 is defined and item.value.layer3

- name: Merge provided configuration with device configuration
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet0/0
        enabled: true
      - name: GigabitEthernet0/1
        enabled: true
      - name: GigabitEthernet0/2
        enabled: true
      - name: GigabitEthernet0/3
        enabled: true
    state: merged