---
- name: set interface descriptions
  cisco.ios.ios_config:
    lines:
      - description {{ item.value.description }}
    parents: "interface {{ item.key }}"
  loop: "{{ lookup('dict', hostvars[inventory_hostname]['interfaces']) }}"

- name: set no switchport
  cisco.ios.ios_config:
    lines:
      - no switchport
    parents: "interface {{ item }}"
  loop: "{{ no_switchport_interfaces }}"

- name: set no ip redirects
  cisco.ios.ios_config:
    lines:
      - no ip redirects
      - no ip unreachables
      - no ip proxy-arp
      - no shutdown
    parents: "interface {{ item }}"
  loop: "{{ layer3_interfaces }}"

- name: set ip addresses
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.key }}"
        ipv4:
          - address: "{{ item.value.ip }}"
    state: merged
  loop: "{{ lookup('dict', hostvars[inventory_hostname]['interfaces']) }}"