---
- name: configure default information originate
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          default_information:
            originate: true
    state: merged

- name: configure ospf process 100
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 100
          areas:
            - area_id: "0"
          network:
            - address: 10.100.0.0
              wildcard_bits: 0.0.0.255
              area: 100

- name: configure router id for process 100
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 100
          router_id: "{{ router_id }}"

- name: configure passive interfaces for process 100
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 100
          passive_interfaces:
            default: true
            interface:
              set_interface: false
              name: GigabitEthernet1/0