---
- name: Merge provided OSPF V2 configuration - Configure Networks
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          areas:
            - area_id: "0"
          network:
            - address: "{{ item.network }}"
              wildcard_bits: "{{ item.mask }}"
              area: 0
  loop: "{{ ospf.networks }}"

- name: Merge provided OSPF V2 configuration - Configure Router ID
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          router_id: "{{ router_id }}"

- name: Merge provided OSPF V2 configuration - Configure Passive Interfaces
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          router_id: "{{ router_id }}"
          passive_interfaces:
            default: true
            interface:
              set_interface: false
              name: "{{ item.key }}"
  loop: "{{ lookup('dict', hostvars[inventory_hostname]['interfaces']) }}"
  when: item.value.active_interface is defined and item.value.active_interface