---
- name: configure ospf process 1569
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          areas:
            - area_id: "0"
          network:
            - address: "{{ item.network }}"
              wildcard_bits: "{{ item.mask }}"
              area: 0
  loop: "{{ ospf.networks }}"

- name: configure router id for process 1569
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          router_id: "{{ router_id }}"

- name: configure passive interfaces for process 1569
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1569
          passive_interfaces:
            default: true
            interface:
              set_interface: false
              name: "{{ item }}"
  loop: "{{ ospf_1569_interfaces }}"